version: '3.8'

services:
   frontend:
      build: ./frontEnd
      ports:
        - 5005:5005
      depends_on:
        - backend
      
   backend:
      build: ./backEnd
      ports:
        - 8080:8080      